apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-sos-backend-prod-pv
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-00c7c7ac1ee6c31a5